@EShop.Presentation_HostAddress = http://localhost:5182

GET {{EShop.Presentation_HostAddress}}/api/Products/  
Accept: application/json
###

GET {{EShop.Presentation_HostAddress}}/api/Products/getFirst 
Accept: application/json
###
